version: '3'
services:

  mongodb:
    image: mongo
    restart: always
    networks: 
        - web

  app:
    build:
        dockerfile: ./app-java.dockerfile
        context: .
    image: robertomassoni/car-protection   
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      APP_DATABASE_URL: mongodb      
    ports:
      - "80:8080"
    networks:
      - web
    depends_on: 
      - mongodb  

networks:
  web:
    driver: bridge
